language: php

php:
    - 5.5
    - 5.4
    - hhvm

before_script:
    - composer install --no-interaction
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - php bin/console assets:install web --symlink
    - php bin/console assetic:dump

script: phpunit -c app/phpunit.xml.dist
