# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    salavert.twig.time_ago:
        class: Salavert\Twig\Extension\TimeAgoExtension
        arguments: [@translator]
        tags:
            - { name: twig.extension }
    chobie_sundown_render:
        class: Sundown\Render\HTML
        arguments: ["%markdown_config%"]
    chobie_sundown_markdown:
        class: Sundown\Markdown
        arguments: ["@chobie_sundown_render", "%markdown_config%"]
    destruktiv_markdown:
        class: Destruktiv\ForumBundle\Twig\Extension\MarkdownExtension
        arguments: [@chobie_sundown_markdown]
        tags:
            - { name: twig.extension }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
